language: objective-c
osx_image: xcode7.2
script:
    - xcodebuild clean build test -workspace GaugeKit.xcworkspace -scheme GaugeKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6'

notifications:
  email:
    recipients:
      - sky4winder+GaugeKit@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
